"""
Class to handle the OAuth token generated by Twitch
"""

import time


class Token:

    def __init__(self, token, refresh_token):
        
        self.token = token
        self.refresh_token = refresh_token
        self.validated = False
        self.validated_time = None

    def validate(self):
        """Set the token's validation fields"""
        self.validated = True
        self.validated_time = time.time()

    @property
    def is_valid():
        """Check if the token has to be validated as per Twitch regulation"""
        if self.validated_time is None:
            return False
        
        return self.validated == True and (time.time() - self.validated_time < 3600)
